### ISSUE TITLE
trouble on configuring docker instance

### ISSUE THREAD

**Issue by dvision1979** [mezz64/ConvertEAC3-Emby#1]
Hello and thank you for sharing your work!

I am trying to run your docker image. I have successfully downloaded it and imported into docker.
When trying to run it with `docker run --net="bridge" -e "EMBY_URL"="http://172.16.1.5:8096" -e "EMBY_API_KEY"="**************************" -e "EMBY_USER_KEY"="*****" -e "EMBY_UNC"="//172.16.1.5/store" -v "/config_path":"/config" -v "/local_path":"/store/store/series" mezz64/converteac3-emby` I get:
```
 ------------------------Starting container ------------------------


Traceback (most recent call last):
  File "emby_eac3.py", line 210, in <module>
    main()
  File "emby_eac3.py", line 177, in main
    episode_list = response.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Stopping Container..
```

I am pretty sure I am not providing some parameters the right way. Could please help?
Thank you in advance.
Regards,
Dan

**Comment by dvision1979** [comment]
I found the problem. I was providing the user name instead of the user id. Now it seems to function.
